// <auto-generated />
using System;
using Housekeeper.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Housekeeper.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220919175825_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Housekeeper.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PreviousUserIndex")
                        .HasColumnType("integer")
                        .HasColumnName("previous_user_index");

                    b.Property<DateTime>("StartOfFirstWeekMidday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_of_first_week_midday");

                    b.Property<decimal[]>("UserIds")
                        .HasColumnType("numeric(20,0)[]")
                        .HasColumnName("user_ids");

                    b.Property<int>("WeekFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("week_frequency");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.ToTable("jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
